### ISSUE TITLE
guardianui / gatewayui: Replace list of hosts in ingress with map

### ISSUE THREAD

**Issue by ngutech21** [ngutech21/fedimint-charts#2]
Replace the hosts list with a map. This simplifies setting the host using terraform or --set in the cli.

``` 
 ingress:
      enabled: false
      className: ""
      annotations: {}
      hosts:
        - host: web.fedimint-1.mydomain.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
```
